version: "3.9"
services:
  jenkins:
    image: jenkins/jenkins:lts
    user: root # :warning: Do not use in production :warning:
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/bin/docker
volumes:
  jenkins_home: {}
